server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydata?characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #关闭缓存，即时刷新，上线生产环境可改为true
    cache: false
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/templates/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${webConfig.upload-path}
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
#自定义路径
webConfig:
  upload-path: D:/uploadFile/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
